
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database_name 
    username: username # your username
    password: password # your password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true